name: Deploy frontend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker build -t towfiq22/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true towfiq22/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Docker-react-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-598130727862
          region: ap-southeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
